### PR TITLE
Enable azure-cli in dockerfile and add to the builds

### PR DESCRIPTION
**Pull request by markodjukic**
### Brief description:

* This PR enables the build of azure-cli in the docker image, using the AZURE=yes arg
* azure-cli is added using pip install, with some additional build dependencies which are cleaned up after the install
* Makefile has been changed to allow for the builds of the azure-cli images

### CODE REVIEW

**Review by ChristophShyper — APPROVED** [review]
Thank you so much @markodjukic. I haven't had time to create Azure account and check for minimal working installation of its CLI. This is so useful.

**Comment by markodjukic** [comment]
No worries, glad to help. I didn't go into modifying the README file to add the instructions for the flavours, didn't want to hack at it, but happy to send a separate PR for that too for your review.

**Comment by ChristophShyper** [comment]
That would be too much :) I've already updated docs and split cloud CLIs into separate layers so it would be faster to rebuild between different flavours.

**Comment by markodjukic** [comment]
You rock. I see the docs, looking good.

**Pull request merged**
